### ISSUE TITLE
Add option to clear out old builds and artefacts

### ISSUE THREAD

**Issue by Floppy** [theodi/master-builder#13]

**Comment by pikesley** [comment]
is this just an aspiration, or do we know how to do this?

I really must change my gravatar

**Comment by Floppy** [comment]
it's a one-liner in the DSL: https://github.com/jenkinsci/job-dsl-plugin/wiki/Job-DSL-Commands. See `logRotator`.

**Comment by Floppy** [comment]
We should also clear out workspaces. We could use the https://wiki.jenkins-ci.org/display/JENKINS/Workspace+Cleanup+Plugin plugin to remove workspaces after every build, with the config from https://groups.google.com/forum/#!searchin/job-dsl-plugin/workspace/job-dsl-plugin/X5h-gwwylJs/fsb5CNHWyAkJ.

**Comment by pikesley** [comment]
The plugin is installed, will add this config to master-builder tomorrow

**Comment by Floppy** [comment]
Done!
